######################################################################
# Automatically generated by qmake (3.0) Sun Feb 22 04:10:44 2015
######################################################################

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = textbrowser
INCLUDEPATH += .

# Input
SOURCES += TextBrowser.cpp
