######################################################################
# Automatically generated by qmake (3.0) Sun Feb 22 04:08:15 2015
######################################################################

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = lcdnumber
INCLUDEPATH += .

# Input
SOURCES += LCDNumber.cpp
