######################################################################
# Automatically generated by qmake (3.0) Sun Feb 22 04:20:28 2015
######################################################################

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = combobox
INCLUDEPATH += .

# Input
SOURCES += ComboBox.cpp
