######################################################################
# Automatically generated by qmake (3.0) Sun Feb 22 04:19:10 2015
######################################################################

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = lineedit
INCLUDEPATH += .

# Input
SOURCES += LineEdit.cpp
