######################################################################
# Automatically generated by qmake (3.0) Sun Feb 22 04:29:42 2015
######################################################################

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = v4l2qt
INCLUDEPATH += .

# Input
HEADERS += bmpHeader.h
SOURCES += v4l2qt.cpp
