######################################################################
# Automatically generated by qmake (3.0) Sun Feb 22 04:09:01 2015
######################################################################

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = progressbar
INCLUDEPATH += .

# Input
SOURCES += ProgressBar.cpp
