######################################################################
# Automatically generated by qmake (3.0) Sat Feb 21 23:03:17 2015
######################################################################

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = qtImageViewer
INCLUDEPATH += .

# Input
SOURCES += qtImageViewer.cpp
