######################################################################
# Automatically generated by qmake (3.0) Wed Jul 15 08:26:14 2015
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = rpi8
INCLUDEPATH += .

# Input
HEADERS += withPi.h bmpHeader.h
SOURCES += withPi.cpp bmpCapture.c
LIBS += -lpthread -lwiringPi
