######################################################################
# Automatically generated by qmake (3.0) Sun Feb 22 03:56:04 2015
######################################################################

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = helloworld
INCLUDEPATH += .

# Input
SOURCES += helloworld.cpp
