######################################################################
# Automatically generated by qmake (3.0) Sun Feb 22 04:00:46 2015
######################################################################

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = customwidget
INCLUDEPATH += .

# Input
HEADERS += CustomWidget.h
SOURCES += CustomWidget.cpp main.cpp
