######################################################################
# Automatically generated by qmake (3.0) Sun Feb 22 04:23:38 2015
######################################################################

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = slider
INCLUDEPATH += .

# Input
SOURCES += Slider.cpp
