######################################################################
# Automatically generated by qmake (3.0) Sun Feb 22 04:22:39 2015
######################################################################

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = dial
INCLUDEPATH += .

# Input
SOURCES += Dial.cpp
