######################################################################
# Automatically generated by qmake (3.0) Sun Feb 22 03:57:55 2015
######################################################################

QT       += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = button
INCLUDEPATH += .

# Input
SOURCES += button.cpp
